### ISSUE TITLE
Most closing labels are missing in C++ files, only a few appear

### ISSUE THREAD

**Issue by Yzrsah** [Finki007/LabelClosing#1]
In C++ code most of the closing labels are missing. Only a few labels appear regardless of the setting for the amount of lines.

**Comment by Finki007** [comment]
Hey @Zyrsha,
yes, this is because I use the abstract syntax tree (ast) of typescript to analyze the code. It analyzes the code as if it were JS or TS code.
You could send me a code snippet to reproduce this.
