### ISSUE TITLE
Grouping Labels to The End of Row

### ISSUE THREAD

**Issue by ChekTek** [Finki007/LabelClosing#2]
Hello! I love your extension! This is more of a feature request than an issue, and I'm not sure how feasible it would be, but what do you think of a setting to move the comment to the end of the line? There are quite a few cases where I run into parenthesis and braces opening a statement, so the extension labels before the closing parenthesis. It would be nice to have a setting to push the closing parethesis and brace together and have the label at the end. I consistently miss the closing parenthesis when copy and pasting etc. 

Example:
![image](https://user-images.githubusercontent.com/6678919/87972320-ad51a100-ca94-11ea-9070-b41567c91725.png)

![image](https://user-images.githubusercontent.com/6678919/87972250-98750d80-ca94-11ea-960f-55450edc4a60.png)

**Comment by Finki007** [comment]
Hey ChekTek,
First of all I would like to thank you for your kind words about my small extension. 
Regarding your request/error:
Could you send me a file where this is the case and best also what settings you have in the extension config. Unfortunately I cannot reproduce it in my environment.

<img width="302" alt="Bildschirmfoto 2020-07-21 um 10 01 01" src="https://user-images.githubusercontent.com/11229398/88029050-c3fe0380-cb39-11ea-90d1-622682f718d9.png">

**Comment by ChekTek** [comment]
Thanks for the quick response. The file I was working on was a pretty standard typescript file. I think this may be a conflict with a different extension I have installed. I disabled the Gitlens extension, reloaded VSCode and it was then working as expected. I enabled Gitlens again and it is still working as expected, so I'm not sure what the root cause of the issue was, but it seems to have resolved itself. Here is a list of the settings I have for VSCode, but I think you could probably close this.

```json
{
  "gitlens.codeLens.enabled": false,
  "gitlens.currentLine.enabled": false,
  "gitlens.views.compare.location": "scm",
  "gitlens.views.fileHistory.location": "scm",
  "gitlens.views.lineHistory.location": "scm",
  "gitlens.views.repositories.location": "scm",
  "gitlens.views.search.location": "scm",
  "activitusbar.views": [
    {
      "name": "explorer",
      "codicon": "files"
    },
    {
      "name": "search",
      "codicon": "search"
    },
    {
      "name": "scm",
      "codicon": "source-control"
    },
    {
      "name": "extension.todo-tree-container",
      "octicon": "tasklist"
    }
  ],
  "todo-tree.tree.showScanModeButton": false,
  "todo-tree.highlights.enabled": true,
  "bracket-pair-colorizer-2.colors": [],
  "bracket-pair-colorizer-2.scopeLineCSS": [
    "borderStyle : solid",
    "borderWidth : 2px",
    "borderColor : #876183",
    "opacity: 1"
  ],
  "todo-tree.general.tags": ["TODOZ", "TODO"],
  "window.zoomLevel": 0,
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "git.enableSmartCommit": true,
  "labelClosing.amountOfLines": 20,
  "diffEditor.ignoreTrimWhitespace": false,
  "git.confirmSync": false,
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "workbench.editor.enablePreviewFromQuickOpen": false,
  "workbench.editor.enablePreview": true,
  "editor.foldingHighlight": false,
  "wallaby.colors": {
    "covered": "#62b455",
    "errorPath": "#ffa0a0",
    "errorSource": "#fe536a",
    "notCovered": "#cccccc",
    "partiallyCovered": "#d2a032"
  },
  "typescript.preferences.importModuleSpecifier": "auto",
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/*.code-search": true,
    "**/.history": true
  },
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/.history": true
  },
  "testExplorer.codeLens": false,
  "testExplorer.errorDecoration": false,
  "testExplorer.gutterDecoration": false,
  "workbench.activityBar.visible": true,
  "eslint.format.enable": true,
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.suggestSelection": "first",
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
  "wallaby.startAutomatically": false,
  "editor.renameOnType": true,
  "typescript.updateImportsOnFileMove.enabled": "always"
}
```
![image](https://user-images.githubusercontent.com/6678919/88093818-91b3cc80-cb60-11ea-9219-76e66aa38e96.png)

**Comment by Finki007** [comment]
Okay, let me know if it happens again. 👍
